### ISSUE TITLE
Custom array in data property

### ISSUE THREAD

**Issue by giordanni612** [tealpartners/ng-select2#11]
Can I pass a custom type array in data property, and define which string attribute in the model will be displayed in dropdown? I tried to use formatSelection, formatResult, templateSelection and templateResult, but no luck.

**Comment by icecoldfire** [comment]
Hey,

I have added an example for a custom array in the data property:

- Demo: https://tealpartners.github.io/ng-select2/
- Code: https://github.com/tealpartners/ng-select2/tree/master/src/app/demos/custom-array

More info over using select2 options: https://select2.org/configuration/options-api

**Comment by giordanni612** [comment]
@icecoldfire, is this commit (0dc87af) published at npm? I'm experimenting the same old issue: when no value is selected (initially), the control becomes very small vertically
![Screenshot (220)](https://user-images.githubusercontent.com/46970296/63783516-25cad480-c8bb-11e9-82ef-307321f1a755.png)

**Comment by icecoldfire** [comment]
0dc87af2a372d733846f7400ec45a669a87bbfd7 is not published on NPM because I didn't change any code to the package. Only the demo component was added.

Could you please share your code so that I can take a look?

**Comment by giordanni612** [comment]
In html:
```
<ng-select2 name="PreferredLanguage" [(ngModel)]="appRequest.participant.preferredLanguage"[options]="options" [width]="'100%'" [data]="helpersService.languages" [placeholder]="'Select...'">
</ng-select2>
```
-----------
In ts:
```
options = {
	templateSelection: (object: any) => {
		return object && object.name;
	},
	templateResult: (object: any) => {
		return object && object.name;
	}
};
```
------
'appRequest.participant.preferredLanguage' has type 'IdNamePair' and 'helpersService.languages' has type 'IdNamePair[ ]'
`export class IdNamePair {
	constructor(public id: number, public name: string) { }
}`

**Comment by giordanni612** [comment]
@icecoldfire , also, with this approach search functionality is broken.  It always filter 'No results found'

**Comment by icecoldfire** [comment]
ngModel doesn't accept an object but the id of that object.

In the [code ](https://github.com/tealpartners/ng-select2/blob/master/projects/ng-select2/src/lib/ng-select2.component.ts )you will see that:

`@Input() value: string | string[];`

the input value is from type string or a array of strings.

I think this is the correct html:

```
<ng-select2 name="PreferredLanguage"
	[(ngModel)]="appRequest.participant.preferredLanguage.id" 		
	[options]="options" 
	[width]="'100%'" 
	[data]="helpersService.languages" 
	[placeholder]="'Select...'">
</ng-select2>
```

**Comment by giordanni612** [comment]
@icecoldfire I tried this way, but the issue with filtering remains

**Comment by icecoldfire** [comment]
@giordanni612 What happens when you use the demo example?

**Comment by icecoldfire** [comment]
Closed because there was no feedback of the reporter.

**Comment by giordanni612** [comment]
Sorry for the delay. I haven't had time to test your example. Finally, I'm currently using it in this way:
<ng-select2 [ngModel]="address.country?.id" [width]="'100%'"
        [data]="helpersService.displayCountries()" [placeholder]="'Select...'"
        (valueChanged)="address.country=helpersService.countries[$event.data[0].element.index]">
      </ng-select2>
