### ISSUE TITLE
changeValue does not fire

### ISSUE THREAD

**Issue by jeboersema** [tealpartners/ng-select2#14]
On the latest version (1.2.1) the changeValue event does not fire when a value is selected.

On version 1.1.2 it does work.

**Comment by icecoldfire** [comment]
Could you open the [new demo 8](https://tealpartners.github.io/ng-select2/) and check that the issue is fixed? 

https://github.com/tealpartners/ng-select2/tree/master/src/app/demos/value-changed

**Comment by jeboersema** [comment]
Yes it is working again. 

Thanx

**Comment by jonasduever** [comment]
@icecoldfire Pretty sure `$event` in `valueChanged` was an object with `value` and `data` before. Is the change to `string` intended and will it stay like this?
_Edit:_ Change was from 1.1.2 to 1.2.0. I'd expect to bump the **major** version when interfaces change.

**Comment by icecoldfire** [comment]
Yes, this was fixed in version 1.2

**Comment by icecoldfire** [comment]
Documentation had always stated: 

### Outputs
* **valueChanged** `string`: Emitted when value changes in select 2 drop down 

This was an bug and fixed in v1.2.0, there were no breaking changes

**Comment by jonasduever** [comment]
@icecoldfire Okay, thank you for the quick clarification!
