### ISSUE TITLE
 I have a problem with the ngmodel, it tells me that I have to have a name

### ISSUE THREAD

**Issue by Markuz1995** [tealpartners/ng-select2#15]
I would like to know if you can help me see how to solve this case.

<ng-select2 [name]="roles" [data]="arrayDataRoles" [(ngModel)]="staffService.selectedStaff.roles" [placeholder]="'Seleccione los roles'" [width]="100" [options]="options"></ng-select2>

I use a name because it is what the error asks me.

ERROR Error: If ngModel is used within a form tag, either the name attribute must be set or the form
      control must be defined as 'standalone' in ngModelOptions.

      Example 1: <input [(ngModel)]="person.firstName" name="first">
      Example 2: <input [(ngModel)]="person.firstName" [ngModelOptions]="{standalone: true}">

I appreciate the help of knowing how to put the name to the input, or what solution could apply.

**Comment by icecoldfire** [comment]
You are attaching the variable `roles` to the name. What is the value of this variable? Could you try this code, if you don't want to use the variable? 
```
<ng-select2 name="roles" 
[data]="arrayDataRoles" 
[(ngModel)]="staffService.selectedStaff.roles" 
[placeholder]="'Seleccione los roles'"
[width]="100"
[options]="options">
```

If this is not working please provide a minimal reproducible example using stackblitz.

**Comment by Markuz1995** [comment]
Ready it works, thanks to adding the name like this, as I'm just starting I didn't know that this attribute could be integrated like this, thank you very much for the prompt response.
