### ISSUE TITLE
Custom search function

### ISSUE THREAD

**Issue by niloy369** [tealpartners/ng-select2#2]
How do i use a custom search function

**Comment by icecoldfire** [comment]
This feature (https://select2.org/searching) is not supported. You are free to make an pull request.

**Comment by niloy369** [comment]
got it working by adding matcher function

`select2Options = {
            multiple: true,
            matcher: this.matchCustom
        };`

the matcher function

`matchCustom(params, data, option){
        return option.text.search(params) !== -1 || option.email.search(params) !== -1;
    }`


here the params is the query string, data is the text displayed and the option parameter holds the object

**Comment by giordanni612** [comment]
@niloy369 Hi, there. When I try to define matcher function, I got the following error:
Error: undefined missing select2/compat/matcher.
My options:
options: any = {
    templateSelection: (object: any) => {
        return object && object.name;
    },
    templateResult: (object: any) => {
        return object && object.name;
    },
    matcher: (params: any, data: any, option: any) => {
        return option.name.search(params) !== -1;
    }
};
Can you be more specific in how do you used it?

**Comment by niloy369** [comment]
> @niloy369 Hi, there. When I try to define matcher function, I got the following error:
> Error: undefined missing select2/compat/matcher.
> My options:
> options: any = {
> templateSelection: (object: any) => {
> return object && object.name;
> },
> templateResult: (object: any) => {
> return object && object.name;
> },
> matcher: (params: any, data: any, option: any) => {
> return option.name.search(params) !== -1;
> }
> };
> Can you be more specific in how do you used it?

try updating the select2 package to version 4
