### ISSUE TITLE
select2 is not defined?

### ISSUE THREAD

**Issue by paragyelonde** [tealpartners/ng-select2#21]
Whenever I am trying to select2  code on the live website its throw error "$select2() is no defined."
but the same code is finely working on my local environment.

**Comment by icecoldfire** [comment]
I don't understand the issue could you please make a minimal reproducible example using stackblitz.com?

What is the behaviour you expect?

**Comment by paragyelonde** [comment]
When I am running my angular 7 project on localhost select2 works perfectly without any error, but as soon as I make my project live on AWS it gives the error "$select2() is not defined."

**Comment by icecoldfire** [comment]
It looks like you don't load the select2 library. 

See: https://stackoverflow.com/a/20586989/3576578
