### ISSUE TITLE
valueChanged seems to trigger before the actual value has changed, causing any check on the value to get the last one instead of the new one.

### ISSUE THREAD

**Issue by MahmoudThePeltist** [tealpartners/ng-select2#28]
I'm using the latest version of ng-select2 in angular8, this is how I'm using it:

`<ng-select2 name="item_type" id="item_type"
			[placeholder]="'Item Type...'"
			[(ngModel)]="item_type"
			(valueChanged)="send_item_type()"
			[data]="item_types_array">		
</ng-select2>`

if I check the value of `item_type` in the `send_item_type()` I get the old one instead of the new one, is there any way to solve this?

edit: code formatting

**Comment by icecoldfire** [comment]
This is as designed, you can check this [demo ](https://github.com/tealpartners/ng-select2/tree/master/src/app/demos/value-changed)out to see how to work with the `valueChanged: EventEmitter<string | string[]>`.
