### ISSUE TITLE
Nested options

### ISSUE THREAD

**Issue by giordanni612** [tealpartners/ng-select2#3]
Hi, there.
When I try to add nested data, the options are not selectable. Maybe I'm doing in the wrong way.
I build data array like this: 
[{'text': 'Cat 1', 'children': [{ 'text': 'Option 1' }] }]
Is this the right way?

**Comment by icecoldfire** [comment]
Did you find the issue? I think the issues came by that you not used a id.

**Comment by giordanni612** [comment]
Thanks. That's exactly what was happening. But now, I would like to know if is necessary the 'id' in group like in the example using getChangeList(), even when the groups have the same 'id' attribute value.
