### ISSUE TITLE
No valueChanged Update with Browser Autocomplete

### ISSUE THREAD

**Issue by EpicVoyage** [tealpartners/ng-select2#33]
I am using ng-select2 for a state dropdown in an address form. If the user selects an address saved for the browser to auto-fill, the ng-select2 state dropdown is populated as well.

Unfortunately (valueChanged) is never called in this scenario where the browser updates the underlying dropdown. There seems to be no way to get the value that the browser populated.

**Comment by icecoldfire** [comment]
Can you share a code example where Chrome or FireFox does the auto-fill? It will be great if you also add a screen recording. 

I tried a few things but I can't reproduce the issue.

**Comment by EpicVoyage** [comment]
Hi, sorry for the delay in replying. I do appreciate your looking into this issue, and I finally had time to get back to this. Here is a screen recording of the issue:

https://drive.google.com/file/d/1pQwY1dJ4lXCBeo0iRnIiufO5Ae9ITQUk/view

As you can see, when Chrome autofills the address, the select2 dropdown displays a value but that is not returned to Angular.

I have implemented a potential fix here, including the demo code used in the video:

https://github.com/EpicVoyage/ng-select2/commit/5bfee8ef71d4e4e839aa11463c4da090b2c56a95

The addition of the element ID would be useful since I have had to resort to hacks to add it in my project, but it is a second change. If you let me know which elements of my code changes you want (if any), I would be happy to create a pull request.

**Comment by EpicVoyage** [comment]
After testing this further on my project, it looks like a second code change is required to prevent recursive change events with some child components:

https://github.com/EpicVoyage/ng-select2/commit/521ba063087ecf68476ac1d06185fb91b914df5d
