### ISSUE TITLE
Support for SSR

### ISSUE THREAD

**Issue by soerenuhrbach** [tealpartners/ng-select2#4]
While trying to use server side rendering in my angular 8 application I got following error message:

`TypeError: Cannot read property 'off' of at NgSelect2Component.ngOnDestroy`

Since jQuery does not work on server side 'this.element' is not defined.
When NgSelect2Component.ngOnDestroy is called, there is not validation that 'this.element' is defined.

By adding a simple validation the bug has been fixed. 

#5

**Comment by icecoldfire** [comment]
#5 has been merged
