### ISSUE TITLE
Change the touched attribute to reflect on blur

### ISSUE THREAD

**Issue by zakarea-Tfaili** [tealpartners/ng-select2#43]
As with normal inputs, the "touched" property is set to true after blurring for the first time on the element.
ng select2 is marked as touched after selecting a value for the first time.
As for validation, I am adding the error if the element is touched and invalid but this is not working with ng-select2 since touched is keeping false.
The normal select input is marked touched after blur.

**Comment by icecoldfire** [comment]
# This package is archived and no longer maintained 
You can use [@ng-select/ng-select](https://github.com/ng-select/ng-select) as replacement.
