### ISSUE TITLE
NG0100: Expression has changed after it was checked

### ISSUE THREAD

**Issue by zakarea-Tfaili** [tealpartners/ng-select2#45]
I am using ng-select2 inside a helper controller

export class DropdownInputComponent implements ControlValueAccessor, OnInit {
@Input() data: Array<Select2OptionData>;
.
.
.
constructor(@Self() public ngControl: NgControl, private elementRef: ElementRef) {
    this.ngControl.valueAccessor = this;
  }
.
.
.

}

when adding [formControl]="ngControl.control" to the ng-select2 component and the data is returned by 
this.structureService.getAvailableStructures().subscribe(response => {
      this.structures = response;
 });

An error  ExpressionChangedAfterItHasBeenCheckedError is thrown

**Comment by icecoldfire** [comment]
Angular issue: https://angular.io/errors/NG0100

Please first fix this issue, then create a reproducible demo.
