### ISSUE TITLE
How to change options for ng-select2 that's already initialized?

### ISSUE THREAD

**Issue by alexaka1** [tealpartners/ng-select2#48]
My component sets up the options for my ng-select2, however I would like to change some options later, based on user input.

Currently I can't even do it, if I just change something like `this.options.ajax.data = (params) => /*whatever*/;`, the change doesn't reflect on ng-select2 components that have already been set up. 
For new ones it works, if I dynamically add new ng-select2s and use this same Options instance but with the changed properties, then that select2 will have the changes applied, but not the existing one(s).

Is there a way to provide the `[options]` as a promise, or something? This is usually how this problem gets solved in other angular components, eg.: angular-datatables.

Or what is the correct method to change options for an existing ng-select2 component (without outright removing it from the DOM and adding it again from scratch)?

**Comment by icecoldfire** [comment]
# This package is archived and no longer maintained 
You can use [@ng-select/ng-select](https://github.com/ng-select/ng-select) as replacement.
