### ISSUE TITLE
ng build failed ng-select2 version 1.2.7

### ISSUE THREAD

**Issue by atulgupt** [tealpartners/ng-select2#56]
error TS2307: Cannot find module 'Select2' or its corresponding type declarations.

4 import { Options } from 'Select2';

https://www.npmjs.com/package/ng-select2/v/1.2.7

 import { Options } from 'Select2';
select2Options: Options = {
         ...{
             multiple: true,
             matcher: this.matchCustom,
             tags: false,
             placeholder: this.placeholder,
            language: {
                 noResults: function () {
                     return this.getTranslateTag(
                        'installer_dashboard.users.add_user.no_results_found'
                     );
                 },
           },
             templateSelection: this.formatState,
         }
     };

![image](https://user-images.githubusercontent.com/14821180/133078944-cfe5886b-ab74-40a0-afad-0c957f4fdd85.png)

**Comment by icecoldfire** [comment]
Upgrade to the latest version (1.2.8) and install the peer dependencies:

```
    "@types/jquery": "3.5.x",
    "@types/select2": "^4.0.x",
    "select2": "^4.0.x",
    "jquery": "3.5.x"
```
https://github.com/tealpartners/ng-select2/blob/master/projects/ng-select2/package.json
