### ISSUE TITLE
Error: The target entry-point "ng-select2" has missing dependencies:  - Select2

### ISSUE THREAD

**Issue by Dineshrajaa** [tealpartners/ng-select2#57]
Hi Team,

I was trying to install ng-select2 package in one of my Angular-12.2.7 application, I am being shown with the following message even though I had installed select2 package and listed it in angular.json scripts and styles.

`node_modules/@angular/compiler-cli/ngcc/src/entry_point_finder/targeted_entry_point_finder.js:40
                throw new Error("The target entry-point \"" + invalidTarget.entryPoint.name + "\" has missing dependencies:\n" +
                ^

Error: The target entry-point "ng-select2" has missing dependencies:
 - Select2`
![image](https://user-images.githubusercontent.com/7291567/135288834-26f84806-4ff5-4e62-aa80-dae30aeb63eb.png)

**Comment by ashish-markelytics** [comment]
I am also facing the same issue while running ng build --prod even if i have added these dependencies in the package as well as angular.json.

**Comment by Cfvillarroel** [comment]
same problem here, can't make it work yet

**Comment by jsonpj3wt** [comment]
bump on this.  Having the same problem.  Any news on this?  Btw, this appears to be an issue with Linux systems only.  Works fine on windows/mac so my guess is it is a path issue but trying to dig through ng-select2 to figure it out.

**Comment by IRCraziestTaxi** [comment]
I believe I found the cause of the issue and opened a pull request for the fix.

https://github.com/tealpartners/ng-select2/pull/58

**Comment by icecoldfire** [comment]
Thank you for the contribution @IRCraziestTaxi! The fix is released under version v1.2.8. I can't reproduce the issue so let me know if this issue isn't resolved.
