### ISSUE TITLE
When click on clear button, Open drop down again

### ISSUE THREAD

**Issue by ChathuraIshanDilhara** [tealpartners/ng-select2#59]
When user click on clear button (allowclear: true), ng-select2 open drop again. If user wants to change the value, user never click clear icon. so it's better to stop that option or give a option to enable whether user wants re-open drop down again or not.

**Comment by icecoldfire** [comment]
Hey @ChathuraIshanDilhara 

This looks like an bug report could you please fill in the [following template](https://raw.githubusercontent.com/tealpartners/ng-select2/master/.github/ISSUE_TEMPLATE/bug_report.md)?

Thank you for opening this issue!
