### ISSUE TITLE
2 issues on drop down list

### ISSUE THREAD

**Issue by ChathuraIshanDilhara** [tealpartners/ng-select2#60]
1. When drop down the list and scroll down the page, drop down list get separated. (1st Image)
2. When pop the spinner, only dropdown list show in front of spinner (I have changed z-index but it's not working). (2nd Image)
Please refer the blow attached images.

**1st Image**
![1](https://user-images.githubusercontent.com/77329481/142728886-9d32ded5-0d70-4ec5-b3ca-28b730d85b0a.jpg)

**2nd Image**
![2](https://user-images.githubusercontent.com/77329481/142728905-65e18e37-3e9f-4065-a7b3-5a562c379829.png)

**Comment by icecoldfire** [comment]
Hey @ChathuraIshanDilhara 

This looks like an bug report could you please fill in the [following template](https://raw.githubusercontent.com/tealpartners/ng-select2/master/.github/ISSUE_TEMPLATE/bug_report.md)?

Thank you for opening this issue!
