### ISSUE TITLE
No valueChanged Update with Browser Autocomplete

### ISSUE THREAD

**Issue by EpicVoyage** [tealpartners/ng-select2#61]
# 🐞 Bug report

### Is this a regression?

No.

### Description

Browser auto-complete can fill the dropdown, but Angular never receives the value.

## 🔬 Minimal Reproduction

Video of issue: https://drive.google.com/file/d/1pQwY1dJ4lXCBeo0iRnIiufO5Ae9ITQUk/view

Reproduction code in testable form: https://github.com/EpicVoyage/ng-select2/tree/master/src/app/demos/autofill

## 🔥 Exception or Error

None.

## 🌍 Your Environment

<pre><code>
> ng version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 11.2.14
Node: 12.16.3
OS: win32 x64

Angular: 11.2.14
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1102.14
@angular-devkit/build-angular   0.1102.14
@angular-devkit/core            11.2.14
@angular-devkit/schematics      11.2.14
@angular/http                   7.2.16
@schematics/angular             11.2.14
@schematics/update              0.1102.14
rxjs                            6.6.7
typescript                      4.1.5
webpack                         4.43.0
</code></pre>

**Anything else relevant?**

I originally opened this as #33, but did not have the ability at the time to return with more details. Sorry about that.

I have implemented a potential fix here, including the demo code used in the video:

[EpicVoyage@5bfee8e](https://github.com/EpicVoyage/ng-select2/)

The addition of the element ID in my forked code would be useful since I have had to resort to hacks to add it in my project, but it is a second change. If you let me know which elements of my code changes you want (if any), I would be happy to create a pull request.

**Comment by icecoldfire** [comment]
Hey,

I have looked at your fork and the code looks good! You can just make an PR to completely merge the fork.

Thank you for the bug fixing and the best wishes for 2022.

**Comment by icecoldfire** [comment]
Merged in #62
