### ISSUE TITLE
ng-select2 with Reactive Forms

### ISSUE THREAD

**Issue by julian-dimitroff** [tealpartners/ng-select2#63]
Hi guys,
I tried to find something, but everywhere I got, is says that ng-select2 do not support Reactive Forms.
Have you consider implementing that kind of support, or can you tell me if there is an easy workaround for using ng-select2 with Reactive Forms

Best regards,
Julian

**Comment by icecoldfire** [comment]
Hi Julian

We don't have plans to implement reactive forms, But we are always open for an PR.

**Comment by julian-dimitroff** [comment]
Thanks for the quick answer!
