### ISSUE TITLE
Need to add custom class

### ISSUE THREAD

**Issue by abdo-host** [tealpartners/ng-select2#65]
I need to add custom class if value empty like bootstrap is-invalid

https://getbootstrap.com/docs/5.1/forms/validation/#custom-styles

**Comment by icecoldfire** [comment]
Hey @abdo-host 

This looks like an bug report could you please fill in the [following template](https://raw.githubusercontent.com/tealpartners/ng-select2/master/.github/ISSUE_TEMPLATE/bug_report.md)?

Thank you for opening this issue!
