### ISSUE TITLE
Error: The target entry-point "ng-select2" has missing dependencies:  - Select2

### ISSUE THREAD

**Issue by alejocastrillon** [tealpartners/ng-select2#66]
Hi, I'm using a Linux distro and I tried to start my Angular 12 App, one of these dependencies is ng-select2. When I tried to start the app, appear this error.
Error: The target entry-point "ng-select2" has missing dependencies:
 - Select2

**Comment by icecoldfire** [comment]
Hi @alejocastrillon,

This looks like an bug report could you please fill in the [following template](https://raw.githubusercontent.com/tealpartners/ng-select2/master/.github/ISSUE_TEMPLATE/bug_report.md)?

Our latest build on Ubuntu has succeeded: https://github.com/tealpartners/ng-select2/runs/4684717115?check_suite_focus=true

Thank you for opening this issue!

**Comment by icecoldfire** [comment]
Also please try first these steps: https://github.com/tealpartners/ng-select2#prerequisites
