### ISSUE TITLE
Can't bind to 'data' since it isn't a known property of 'ng-select2'.

### ISSUE THREAD

**Issue by afeef1915** [tealpartners/ng-select2#7]
In the 
https://www.npmjs.com/package/ng-select2/v/1.1.2

		import { NgSelect2Module } from 'ng-select2';

		@NgModule({
		  imports: [
			....,
			NgSelect2Module
		  ],
		  ...
		})

github package.json

				
			{
			  "name": "ng-select2",
			  "version": "0.0.0",
			  "dependencies": {
				"@angular/animations": "8.0.1",
				"@angular/common": "8.0.1",
				"@angular/compiler": "8.0.1",
				"@angular/core": "8.0.1",
				"@angular/forms": "8.0.1",
				"@angular/platform-browser": "8.0.1",
				"@angular/platform-browser-dynamic": "8.0.1",
				"@angular/router": "8.0.1",
				"@types/jquery": "3.3.29",
				"@types/select2": "4.0.47",
				"bootstrap": "4.3.1",
				"jquery": "3.4.1",
				"popper.js": "1.15.0",
				"rxjs": "6.5.2",
				"select2": "4.0.7",
				"zone.js": "0.9.1"
			  },
			  "scripts": {
				"ng": "ng",
				"start": "ng serve",
				"build": "ng build",
				"test": "ng test",
				"lint": "ng lint",
				"e2e": "ng e2e",
				"packagr": "ng-packagr -p projects/ng-select2/ng-package.json",
				"packagr-prod": "ng-packagr -p projects/ng-select2/ng-package.prod.json"
			  },
			  "private": true,
			  "devDependencies": {
				"@angular-devkit/build-angular": "0.800.3",
				"@angular-devkit/build-ng-packagr": "0.800.3",
				"@angular/cli": "8.0.3",
				"@angular/compiler-cli": "8.0.1",
				"@angular/language-service": "8.0.1",
				"@types/node": "12.0.8",
				"angular-cli-ghpages": "0.5.3",
				"codelyzer": "5.1.0",
				"ng-packagr": "5.3.0",
				"ts-node": "7.0.1",
				"tslib": "1.9.3",
				"tslint": "5.17.0",
				"typescript": "3.4.5"
			  }
			}

My Package.,json

			 "dependencies": {
			   
				"jquery": "^3.4.1",
				"ng-select2": "^1.1.2",
				"ngx-bootstrap": "^5.1.0",
				"popper.js": "^1.15.0",
				"rxjs": "~6.4.0",
				"select2": "^4.0.8",
				"tslib": "^1.9.0",
				"zone.js": "~0.9.1"
			  },
How can we implement select2 if we don't  reference the NPM package but directly in package json

**Comment by icecoldfire** [comment]
If you get an issue like:

> Can't bind to 'data' since it isn't a known property of 'ng-select2'

It means that you didn't added it to your module (first step in the installation guide...).
If the issue persists please make a minimal reproducible example using https://stackblitz.com/

**Comment by afeef1915** [comment]
I have tried to replicate this stackblitz

ERROR
Error: jQuery is not defined

Jquery is already Installed

![image](https://user-images.githubusercontent.com/16572202/62367962-cb06bd00-b548-11e9-948e-b937e03b12d9.png)

https://stackblitz.com/edit/angular-qsa8le?file=package.json
