### ISSUE TITLE
How to do backend search in ng select2

### ISSUE THREAD

**Issue by afeef1915** [tealpartners/ng-select2#8]
i need to make ajax call .

i need custom search functionality to search records from database.

component.htm

			<ng-select2 [data]="data"
						[options]="options"
						[width]="500",
						[searchFn]="customSearchFn"
					   >DEMO
			</ng-select2>
			<br/>

component.ts

		 customSearchFn(term: string, item) {

			console.log(term);
			console.log(item);

ng2component

			import { AfterViewInit, DoCheck, ElementRef, EventEmitter, NgZone, OnChanges, OnDestroy, OnInit, Renderer2, SimpleChanges } from '@angular/core';
			import { ControlValueAccessor } from '@angular/forms';
			import { Select2OptionData } from './ng-select2.interface';
			import { Options } from 'select2';
			export declare class NgSelect2Component implements AfterViewInit, OnChanges, OnDestroy, OnInit, DoCheck, ControlValueAccessor {
				private renderer;
				zone: NgZone;
				_element: ElementRef;
				selector: ElementRef;
				data: Array<Select2OptionData>;
				placeholder: string;
				dropdownParent: string;
				allowClear: boolean;
				value: string | string[];
				width: string;
				disabled: boolean;
				options: Options;
				valueChanged: EventEmitter<{}>;
				private element;
				private check;
				constructor(renderer: Renderer2, zone: NgZone, _element: ElementRef);
				ngDoCheck(): void;
				ngOnInit(): void;
				ngOnChanges(changes: SimpleChanges): void;
				ngAfterViewInit(): void;
				ngOnDestroy(): void;
				private initPlugin;
				private setElementValue;
				writeValue(value: any): void;
				propagateChange: (value: any) => void;
				registerOnChange(fn: any): void;
				registerOnTouched(): void;
			}

**Comment by nileshsonkusare** [comment]
Hello @afeef1915 

I managed to do backend search in ng-select2.  

Step 1 : component.html

```
<ng-select2 id="select2ID" name="select2ID" [options]="remoteOptions" 
  (valueChanged)="onValueChange($event)" [(ngModel)]="selectedID">
</ng-select2>
```


Step 2: component.ts

```
//Declare globally.
public remoteOptions: Options;
public selectedID: any;
```

bind remote options inside ngOnInit() 

```
 ngOnInit() {

    this.remoteOptions = {
      multiple: false,
      width: "100%",
      theme: 'bootstrap',
      minimumInputLength: 1,
      placeholder: {
        id: "",
        placeholder: 'Search Item...',
      },
      allowClear: true,
      ajax: {
        url: <<Your API URL>>,
        dataType: 'json',
        headers: {
          "Content-Type": "application/json",
          "Authorization": `Bearer <<Your API Access Token if have otherwise skip this >>`
        },
        data: function (params) {
          return {
            q: params.term,
          };
        },
        processResults: function (data, params) {

          //Here data must have array of objects which have "id" & "text" property 	  
          return {
            results: data
          };
        },
        cache: true
      },
      escapeMarkup: function (markup) { return markup; },
      templateResult: this.formatResult,
      templateSelection: this.formatSelection
    }
  }

```
define two more methods formatResult & formatSelection.

```
formatResult(d) {
    return d.text;
 }

formatSelection(d) {
    if (d.id == null || d.id == "" || d.id == undefined) {
      return "Search Item..."; //Default Place holder
    }
    return d.text;
 }

```
`onValueChange(event)` method is call when value of the drop-down changes

```
onValueChange(event) {
   console.log(event);
}
```


Reference Link : https://select2.org/data-sources/ajax

Let me know if you still facing any issue.

Thanks,
Nilesh

**Comment by afeef1915** [comment]
I have manage to do backend search.

But in Angular 8 

After appending data in  [data]="data"  dropdown hides 

html class "select2-container select2-container--default select2-container--open" is opened after click but after binding subscribe response dropdown hides

**Comment by nileshsonkusare** [comment]
@afeef1915 If you wants to load select2 data from back end search then no need to provide [data]="data" 

You can use my solution `[options]="remoteOptions"`. This will load result from back end API when user enters at least one character in select2 dropdown.

Just let me know if you facing any issue on above solution. Thanks!

**Comment by afeef1915** [comment]
Thanks for the help.

i  need to follow the same approach.

after appending subscribe response  dropdown hides.
Link
https://github.com/tealpartners/ng-select2/issues/10

**Comment by icecoldfire** [comment]
I'm closing this issue because @nileshsonkusare has given a good solution, thanks!

I have added this to the wiki: https://github.com/tealpartners/ng-select2/wiki/How-to-do-backend-search-in-ng-select2

**Comment by afeef1915** [comment]
If you accept then remove heading Angular 8.

This is not the way Angular 8 works.

i wasted  week in debugging your plugin which i found unstable .

This is not correct solution for Angular 8.

**Comment by icecoldfire** [comment]
Could you please explain why this issue wasn't resolved? The documentation how that Angular 8 works can you find here: https://angular.io/docs. Feel free to contact us again if you need further assistance.

**Comment by afeef1915** [comment]
try with subscribe and save response [data]="select2data "
					<ng-select2
					[data]="select2data "
					[options]="options"
					[width]="500"
					[formControlName]="field.code"
					(keyup)="changed($event.target.value)"
					>
					</ng-select2>

					changed(search: any) {

					//call service pass search text to service
							return this.cl.searchFunc(search).subscribe(
							res1 => 
							  this.select2data = res1.data;
							  this.cd.markForCheck(); // marks path
							 this.cd.detectChanges();
							}
							}
							},
							error => {
							console.log('error  = ', error);
							});
					}

The way subscribe works.


Problem is after saving subscribe response 

for example sample data

 this.select2data = [
      {
        id: 'multiple1',
        text: 'Multiple 1'
      },
      {
        id: 'multiple2',
        text: 'Multiple 2'
      },
      {
        id: 'multiple3',
        text: 'Multiple 3'
      },
      {
        id: 'multiple4',
        text: 'Multiple 4'
      }
    ];

After subscribe response dropdown hides.

dropdown only visible after you click on textbox that's bug.

Thanks
