### ISSUE TITLE
How to Restrict Multiple Option demo to only one tag

### ISSUE THREAD

**Issue by afeef1915** [tealpartners/ng-select2#9]
<h2>6. Multiple values demo (tags)</h2>

<ng-select2 [data]="exampleData"
            [options]="options"
            [width]="500"
            [(ngModel)]="value">
</ng-select2>
<br/>
<br/> Selected values: {{ value }}

**Comment by icecoldfire** [comment]
Dear

I don't understand the issue could you please make a minimal reproducible example using stackblitz.com?

What is the behaviour you expect?


Is this the option that you want?
``` 
this.options = {
  width: '300',
  multiple: false,
  tags: true
};
```

**Comment by icecoldfire** [comment]
I'm closing this issue for now because there is no response.
